name: Spell checking
on:
  pull_request_target:
  push:
  issue_comment:

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: "!contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
    - name: spelling
      uses: check-spelling/check-spelling@force-values
      with:
        experimental_apply_changes_via_bot: 1
        post_comment: 0
        capture_output_unknown_words: 1
        capture_output_stale_words: 1
        capture_output_skipped_files: 1
    - name: unknown-words
      run: "cat ${{ steps.spelling.outputs.unknown_words }}"
      shell: bash
    - name: stale-words
      run: "cat ${{ steps.spelling.outputs.stale_words }}"
      shell: bash
    - name: skipped-files
      run: "cat ${{ steps.spelling.outputs.skipped_files }}"
      shell: bash
